<%@LANGUAGE="VBSCRIPT" CODEPAGE="1252"%>
<!--#include virtual="/asp/global.inc" -->
<!--#include virtual="/asp/chromehead.inc" -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title><%= pageTitle %></title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="<%= cssDir %>/keyframe.css" rel="stylesheet" type="text/css">
<link href="<%= cssDir %>/fonts.css" rel="stylesheet" type="text/css">
<link href="<%= cssDir %>/layout.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<%= jsDir %>/common.js"></script>
<script type="text/javascript" src="<%= jsDir %>/MM_functions.js"></script>
</head>
<body>
<center>
<div class="topdiv">
<img src="/image/000/top_cap2.gif" class="bottomCap" alt="">
<div class="lrlines">
	<img src="/image/000/postcare/logo_b.gif">
	<p class="lrgred">Disclaimer</p>
	&nbsp;
</div><div class="lrtlines" align="center">
	<table cellpadding="0" cellspacing="10" width="95%"><tr><td align="center">
<textarea class="sml" rows="8" cols="100" wrap="hard">
Before you venture onto the PostCare.com Web site or one of it's sponsers, you need to read the terms of service set out below.  You need to understand our terms and agree to them. 
Terms of Service
1.  PostCare.com may ask for minimal identifying information from you for its own records.  It does not sell user lists.  No one from PostCare.com will ask you for personal financial information.  
2.  PostCare.com is not your physician or a health care provider.  The information provided in this Web site is not for the practice of medicine, and none of our agents, employees or consultants will provide health care services or enter into a clinical or treatment relationship with you.  The information you obtain from PostCare.com should not substitute or be used instead of a relationship with a health care professional.  All Users are encouraged and directed to seek the advice of, and regularly consult with, physicians and other health care professionals of their selection.  All Users acknowledge that the information on the PostCare.com Web site and on its videos is not for use to diagnose, treat, or prescribe medication, nor to diagnose or treat, for any person.  Under no circumstances should PostCare.com's Web site be used or relied upon for making medical diagnoses, or providing any type of medical care or treatment. 
3.  PostCare.com reserves the right to modify or supplement any or all of the terms of its service.  The current terms will remain available on our Web site at any time.  The terms, as amended or modified, shall apply to each User's current or subsequent use of this Web site, as of the date the amendment or modification is posted. 
4.  The application of these provisions, disclosures and disclaimers and all other mattersarising from your use of this Web site or of any information you obtain from PostCare.com shall be governed by the statute and laws of the United States of America and the Commonwealth of Massachusetts.  
5.  Any claims, disputes or other controversies relating to or arising from these provisions, disclosures and disclaimers or from your use of this Web site or any information you receive from PostCare.com shall be brought exclusively in state or Federal Court in the Commonwealth of Massachusetts, and you hereby expressly consent to the exercise of jurisdiction over you by either court. 
6.  To the fullest extent permitted by applicable law, each party to this Agreement waives itsor his right to a jury trial with respect to any action brought under or in connection with this Agreement.
7.  As a prerequisite to filing any lawsuit or complaint against PostCare.com with any state or federal court or administrative agency, you agrees to give written notice of any potential claim to PostCare.com, sent by certified and registered mail toDemetre Samellas, Chairman, MedSelfEd, Inc.,  53 Gray Cliff Road, Newton, MA, 02459, USA  The User acknowledges that such notice is a prerequisite to filing a complaint, and that the failure of the user to provide notice to MedSelfEd, Inc. as set forth above, whether or not the failure to give notice causes any prejudice to MedSelfEd, Inc., extinguishes the claim and shall serve as a basis for dismissal of any action filed without proper notice.  The User further acknowledges that in no event shall any action against PostCare.com stemming from services or information provided by this Web site be commenced more than three years after the access which is the alleged cause of injuryupon which such action is based,regardless of whether the user has knowledge of the injury as of that date. If any clauseor provision set forth above isdetermined to be illegal, invalid or unenforceable under present or future law, then, in that event, you understand and agree that the clause or provision so determined tobeillegal, invalid or unenforceable shallbe severable without affecting the enforceability of all remaining clauses or provisions.
8.  The User represents to PostCare.com that he or she is 18 years of age.
9.  The User agrees not to post any statements or information which is libelous, defamatory, obscene, fraudulent, false or contrary to the ownership or intellectual property rights of any other person, or that contains any virus or other computer code which is contaminated or destructive to the files or programs of PostCare.com or any of its Users or Sponsors.
10.  PostCare.com has agreements with various entities in the health care or related fields, which we call our "Sponsors."  Sponsors may have made arrangements with PostCare.com to post advertisements on our Web site.  PostCare.com does not endorse or warranty the products or services our Sponsors provide, and make no representations or warranties about the type or quality of products or services of our Sponsors.  You should contact or obtain information about or from a Sponsor directly from them through the links on this Web site.  
11.  PostCare.com may include or provide links to other Web sites on the Internet, including, but not limited to, links to Web pages which may include information, opinions or recommendations of various other individuals, organizations or companies.  PostCare.com has no affiliation with such Web sites or the individuals, organizations or companies responsible for them.  In providing such links, PostCare.com does not represent to you that it has investigated the content of such information, opinions or recommendations and the User understands and agrees that PostCare.com does not warrant or guarantee the accuracy of such informationor necessarily subscribe to any such opinions or recommendations. 
12.  PostCare.com strives to be a valuable resource of current medical information for our Users. We cannot ensure that information we provide is exhaustive or complete on every subject or that it will necessarily include all of the most recent informationavailable on aparticular topic.  This information is of a general nature and we urge you to review it with your own physician or health care provider. Users should never delay, ignore or fail to obtain medical advice based on information obtained from PostCare.com.
13.  All text and images Copyright(&copy;) 2002 by MedSelfEd, Inc. The name "PostCare.com " and associated logo are proprietary trademarks and service marks of MedSelfEd, Inc.  The User can downloaded information from the PostCare.com Web site for personal use only. If you would like to request permission to reprint or electronically reproduce any of PostCare.com's information or materials for other than personal use, please contact our Licensing Department at : MedSelfEd, Inc.,53 Gray Cliff Road, Newton, MA, 02459, USA. or "info@PostCare.com" .  
14.  When we receive an email, we make reasonable efforts to respond in as timely a manner as possible but we cannot represent or warrant how quickly we will be able to respond and you should not refrain from seekingmedical treatmentwhile waiting for information from us.  PostCare.com does not guarantee that it will respond to all inquiries, and reserves the right to ignore or delete any information including, but not limited to, information that is fraudulent, abusive, defamatory, obscene or in violation of a copyright, trademark or other intellectual property or ownership right of any other person.
15.  PostCare.com makes efforts to ensure that its Web site is clean of any viruses and similar contaminants, but cannot represent or warranty that its files are free of computer codes that may contaminate or destroy data or other computer parts, programs or information of the User.
16.  PostCare.com's goal is to provide current, accurate information on its Web site, butcannot and does not make such representation or warranty, nor can it represent that that there are no errors, omissions,or other defects in the information supplied to users onits Web site. 
17.  Information supplied by PostCare.com is provided "as is" and neither MedSelfEd, Inc. norany of our staff, includingwithout limitation our physicians and sponsors,  make any representation or warranty with respect to the contents of this Web site or information furnished by them or our agents, employees or representatives and specifically disclaim to the fullest extent permitted by law any and all warranties, express or implied, including, but not limited to, implied warranties of merchantability, completeness, timeliness, correctness, non infringement, or fitness for any particular use, application or purpose.  The User agrees that MedSelfEd, Inc., and its officers, directors, agents and employees, shall not be liable to you for any damages, claims, demands or causes of action, direct or indirect, special, incidental, consequential or punitive, as a result of your use of this Web site or any information you obtain on it or any otherinteraction with PostCare.com's staff, agents, employeesorconsultants.  In doing so, you agree that you are waiving voluntarily and unequivocally any liability of MedSelfEd, Inc. or its agents.
I acknowledge that I have read the provisions, disclosures and disclaimers set forth above, that they are fair and reasonable in exchange for my access to the PostCare.com Website.  My agreement to follow and be bound to these provisions, disclosures and disclaimers is not the result of fraud, duress or undue influence exercised upon me by any person or entity. There are no representations, promises, warranties or undertakings byPostCare.comcontrary to those set forth above.  By clicking on the button below, marked "accept," I acknowledge that I have agreed to all of the above provisions, disclosures, disclaimers, and prerequisites to suit.
</textarea>
<center><br><a href="javascript:;" onclick="history.back(-1)"><img src="/image/000/accept3.gif" border="0"></a></center></td></tr></table>
    </div>
    <img src="/image/000/bottom_cap2.gif" class="bottomCap" alt="">
</div>
</center>
</body>
</html>
<!--#include virtual="/asp/chromefoot.inc" -->
