sHTML = '<table width=100% bgcolor=#005B30 background=Menu-Background.jpg cellpadding=0 cellspacing=0 border=0>';
sHTML = sHTML + '<tr height=20>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label1><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/OHVI/ class=MenuHeader onMouseover=return!showMenu(\'1\',event,\'label1\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>Patient&nbsp;Guide</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu1 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=1a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/PreparingForVisit.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Preparing&nbsp;for&nbsp;Your&nbsp;Visit</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=1b bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/tests.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Tests</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=1c bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/procedures.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Procedures</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=1d bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/CardiacSurgery.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Cardiac&nbsp;Surgery</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=1e bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=CardiacRehab/CardiacRehabMain.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Rehabilitation</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=1f bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/HeartRhythmSvcs.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Heart&nbsp;Rhythm&nbsp;Services</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=1g bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/HeartFailureCenter.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Heart&nbsp;Failure&nbsp;Center</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=1h bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/Classes.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Classes</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=1i bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/Women/default.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Especially&nbsp;for&nbsp;Women</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=1j bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/directions.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Map&nbsp;and&nbsp;Directions</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML + '<td><span style=color=#ffffff>|</span></td>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label2><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/OHVI/YourHeart.htm class=MenuHeader onMouseover=return!showMenu(\'2\',event,\'label2\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>Heart&nbsp;&&nbsp;Vascular&nbsp;Health</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu2 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=2a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/prevention.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Prevention</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2b bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/lifestyle.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Lifestyle:&nbsp;Food&nbsp;&&nbsp;Exercise</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2c bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/PerVenousDisease.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Peripheral&nbsp;Venous&nbsp;Disease</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2d bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/PerArtDisease.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Peripheral&nbsp;Artery&nbsp;Disease</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2e bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/HeartSurgery.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Heart&nbsp;Surgery</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2f bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/AbnHeartRhythm.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Abnormal&nbsp;Heart&nbsp;Rhythm</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2g bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/HeartFailure.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Heart&nbsp;Failure</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML + '<td><span style=color=#ffffff>|</span></td>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label3><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/OHVI/Members.htm class=MenuHeader onMouseover=return!showMenu(\'3\',event,\'label3\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>Member&nbsp;Physicians</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu3 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=3a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/Leadership.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Leadership</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=3b bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/Members.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Membership</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=3c bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/physicians/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Physician&nbsp;Search</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML + '<td><span style=color=#ffffff>|</span></td>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label4><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/OHVI/ReferDocs.htm class=MenuHeader onMouseover=return!showMenu(\'4\',event,\'label4\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>Referring&nbsp;Physicians</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu4 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=4a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/patient_referral.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>How&nbsp;to&nbsp;Refer&nbsp;A&nbsp;Patient</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=4b bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/Oregon/Careers/tour/OpenHeart.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Take&nbsp;A&nbsp;Tour</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=4c bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/QuarterlyNews.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>OHVI&nbsp;Quarterly</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML + '<td><span style=color=#ffffff>|</span></td>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label5><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/OHVI/research.htm class=MenuHeader onMouseover=return!showMenu(\'5\',event,\'label5\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>Research</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu5 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=5a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/research.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Our&nbsp;Research</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=5b bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/ClinicalTrials.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Clinical&nbsp;Trials</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=5c bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/AcademicResearch.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Academic&nbsp;Research</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML + '<td><span style=color=#ffffff>|</span></td>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label6><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/OHVI/About.htm class=MenuHeader onMouseover=return!showMenu(\'6\',event,\'label6\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>About&nbsp;Us</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu6 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=6a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/About.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>About&nbsp;OHVI</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6b bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/Timeline.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Timeline</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6c bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/vision.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Vision&nbsp;Statement</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6d bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/Oregon/careers/tour/OpenHeart.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Take&nbsp;A&nbsp;Tour</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6e bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/outcomes.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Quality&nbsp;Care&nbsp;&&nbsp;Outcomes</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6f bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/directions.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Map&nbsp;&&nbsp;Directions</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6g bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/contact.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Contact&nbsp;Us</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6h bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/donate.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Donate&nbsp;to&nbsp;the&nbsp;Institute</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6i bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/Oregon/WhoWeAreSHMC.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Sacred&nbsp;Heart&nbsp;Medical&nbsp;Center</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6j bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/RiverBend.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>RiverBend&nbsp;Facility</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6k bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/OHVI/careers.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Careers</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML +'<td align=left valign=middle width=100% height=20></td></tr></td></tr></table>';
if(document.all){
menuContents.innerHTML = sHTML;
}else{
document.getElementById("menuContents").innerHTML = sHTML;
}
