sHTML = '<table width=100% bgcolor=#005B30 background=Menu-Background.jpg cellpadding=0 cellspacing=0 border=0>';
sHTML = sHTML + '<tr height=20>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label1><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/apps/news class=MenuHeader onMouseover=return!showMenu(\'1\',event,\'label1\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>What&rsquo;s&nbsp;New</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu1 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=1a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/news onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>News&nbsp;Center</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML + '<td><span style=color=#ffffff>|</span></td>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label2><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/HealthInfo class=MenuHeader onMouseover=return!showMenu(\'2\',event,\'label2\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>Health&nbsp;Information</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu2 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=2a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/kbase/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Healthwise&nbsp;Knowledgebase</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2b bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/subject/Default.asp onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Health&nbsp;Topics&nbsp;-&nbsp;Medline&nbsp;Plus</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2c bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/Expert/Default.asp onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Ask-an-Expert</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2d bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/aal/Default.asp onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Ask&nbsp;a&nbsp;Librarian</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2e bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/links/search.asp onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Health&nbsp;Links</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2f bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/HealthInfo/YourHealth/Assess.asp onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Assess&nbsp;Your&nbsp;Health</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2g bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/course/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Education&nbsp;&&nbsp;Support</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2h bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/quality/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Transparency:&nbsp;Quality</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2i bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/HealthInfo/Women onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Especially&nbsp;for&nbsp;Women</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2j bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/HealthInfo/Seniors onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Especially&nbsp;for&nbsp;Seniors</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=2k bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/HealthInfo/Parents onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Especially&nbsp;for&nbsp;Parents</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML + '<td><span style=color=#ffffff>|</span></td>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label3><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/PatientsAndFamilies class=MenuHeader onMouseover=return!showMenu(\'3\',event,\'label3\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>For&nbsp;Patients&nbsp;&&nbsp;Families</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu3 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=3a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/PatientsAndFamilies/Babies onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>baby@lbum</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=3b bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/cheercards/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Cheer&nbsp;Cards</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=3c bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/postcard/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>E-mail&nbsp;a&nbsp;Patient</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=3d bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/HealthInfo/YourHealth/Assess.asp onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Assess&nbsp;Your&nbsp;Health</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=3e bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/PatientsAndFamilies/Maps onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Maps&nbsp;&&nbsp;Directions</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=3f bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/PatientConnection/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>PatientConnection</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML + '<td><span style=color=#ffffff>|</span></td>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label4><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/apps/physicians/ class=MenuHeader onMouseover=return!showMenu(\'4\',event,\'label4\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>Find&nbsp;a&nbsp;Physician</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu4 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=4a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/physicians/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Physician&nbsp;Directory</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML + '<td><span style=color=#ffffff>|</span></td>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label5><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/AboutPH class=MenuHeader onMouseover=return!showMenu(\'5\',event,\'label5\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>About&nbsp;PeaceHealth</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu5 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=5a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/SpiritPeaceHealth/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Overview-Spirit&nbsp;of&nbsp;PeaceHealth</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=5b bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/SpiritPeacehealth/mission/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Our&nbsp;Mission&nbsp;&&nbsp;Values</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=5c bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/SpiritPeacehealth/Story/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Our&nbsp;History</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=5d bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/AboutPH/OurPromise.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Our&nbsp;Promise</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=5e bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/SpiritPeacehealth/QualityJourney/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Our&nbsp;Quality&nbsp;Journey</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=5f bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/SpiritPeacehealth/HealthSystems/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Communities&nbsp;We&nbsp;Serve</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=5g bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/news/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>News&nbsp;Center</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=5h bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/AboutPH/Foundation/foundations.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Foundations/Planned&nbsp;Giving</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML + '<td><span style=color=#ffffff>|</span></td>';
sHTML = sHTML + '<td nowrap align=left valign=middle height=20>';
sHTML = sHTML + '<div id=label6><img src=shim.gif width=5 height=10 border=0 name=img1><a href=/Careers class=MenuHeader onMouseover=return!showMenu(\'6\',event,\'label6\');menuOver(\'rollimg2\');  onMouseOut=window.status=\'\';return true;><b>Careers</b>&nbsp;</a></div>';
sHTML = sHTML + '<div id=menu6 style=width:150px;height:52px;position:absolute;z-index:1;display:none onmouseover=event.cancelBubble=true;>';
sHTML = sHTML + '<img src=shim.gif width=5 height=3 border=0><table border=0 cellspacing=0 cellpadding=0><tr><td bgcolor=#8b0000 width=100% >';
sHTML = sHTML + '<table border=0 cellpadding=2 cellspacing=0 width=100% >';
sHTML = sHTML + '<tr id=6a bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/SpiritPeaceHealth/Working/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Working&nbsp;at&nbsp;PeaceHealth</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6b bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/jobsonline/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Job&nbsp;Openings</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6c bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/apps/jobsonline/docjobsonline.asp onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Physician&nbsp;Openings</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6d bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/careers/content/TakeTour.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Select&nbsp;a&nbsp;Location</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6e bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/careers/content/co_faq_general.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Employment&nbsp;FAQ</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6f bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/careers/content/contact.htm onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>Contact&nbsp;Human&nbsp;Resources</a>&nbsp;</td></tr> ';
sHTML = sHTML + '<tr id=6g bgcolor=#E2EBF0><td nowrap onMouseover="this.style.backgroundColor = \'#8FB6A3\';" onMouseout="this.style.backgroundColor = \'#E2EBF0\';" width=100% class=MenuBox>';
sHTML = sHTML + '<a class=MenuItem href=http://www.peacehealth.org/SpiritPeaceHealth/ onMouseOut=menuOut(\'rollimg2\'); onMouseOver=menuOver(\'rollimg2\');><img src=shim.gif width=5 height=2 border=0>The&nbsp;Spirit&nbsp;of&nbsp;PeaceHealth</a>&nbsp;</td></tr> ';
sHTML = sHTML + '</table></td></tr></table></div></td>';
sHTML = sHTML +'<td align=left valign=middle width=100% height=20></td></tr></td></tr></table>';
if(document.all){
menuContents.innerHTML = sHTML;
}else{
document.getElementById("menuContents").innerHTML = sHTML;
}
